language: java
jdk:
  - oraclejdk8
env:
  - GRADLE_OPTS="-Dorg.gradle.daemon=false"
services:
   - redis-server
script: 
   - ./gradlew test
   - ./gradlew :gateleen-test:test -PintegrationTests -q
   - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
